### ISSUE TITLE
There is a typo in your README.md

### ISSUE THREAD

**Issue by krynczak** [StarKitty/StarKitty#1]
On your README.md, you have the wrong value in your `employer` variable.

Incorrect:
  `employer: 'MadeiraMadeira'`
Correct:
  `employer: 'Repassa'`

please fix
thanks

**Comment by RoKondo** [comment]
This documentation will be updated on our next monthly update, thanks for the heads up but this issue has already been taken care of.
![image](https://user-images.githubusercontent.com/5970835/117150173-4a649880-ad8e-11eb-81de-209c6f35124e.png)

Stay tuned for more exciting news on our documentation.

Regards,
Kondo.

**Comment by krynczak** [comment]
Thank you friend, you are a friend, friend!
